// <auto-generated />
namespace WebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class creatingHistoryTables4PurchaseAndProduction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(creatingHistoryTables4PurchaseAndProduction));
        
        string IMigrationMetadata.Id
        {
            get { return "201708170339504_creatingHistoryTables4PurchaseAndProduction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
